name: SignBridge
tool: kiro
mode: ai-assisted-development
created_at: 2025-12-29T12:00:00+05:30
updated_at: 2025-12-29T13:45:00+05:30

stack:
  - Next.js
  - TypeScript
  - Web Speech API
  - MediaPipe
  - WebGL

status: demo-stable
